/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceDisclaimerRouteImport } from './routes/marketplace-disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ReportListingRouteImport } from './routes/report-listing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiGoogleCheckRouteImport } from './routes/api/google-check'
import { Route as BuyIndexRouteImport } from './routes/buy/index'
import { Route as DealerSlugRouteImport } from './routes/dealer/$slug'
import { Route as DubaiIntentRouteImport } from './routes/dubai/$intent'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PostIdRouteImport } from './routes/post/$id'
import { Route as RentIndexRouteImport } from './routes/rent/index'
import { Route as SellerSlugRouteImport } from './routes/seller/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ListingsRouteImport } from './routes/api/v1/listings'
import { Route as BuyVehicleIndexRouteImport } from './routes/buy/$vehicle/index'
import { Route as RentVehicleIndexRouteImport } from './routes/rent/$vehicle/index'
import { Route as ApiV1ListingsIdRouteImport } from './routes/api/v1/listings/$id'
import { Route as BuyVehicleAreaIndexRouteImport } from './routes/buy/$vehicle/$area/index'
import { Route as BuyVehicleAreaIdRouteImport } from './routes/buy/$vehicle/$area/$id'
import { Route as RentVehicleAreaIndexRouteImport } from './routes/rent/$vehicle/$area/index'
import { Route as RentVehicleAreaIdRouteImport } from './routes/rent/$vehicle/$area/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceDisclaimerRoute = MarketplaceDisclaimerRouteImport.update({
  id: '/marketplace-disclaimer',
  path: '/marketplace-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportListingRoute = ReportListingRouteImport.update({
  id: '/report-listing',
  path: '/report-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCheckRoute = ApiGoogleCheckRouteImport.update({
  id: '/api/google-check',
  path: '/api/google-check',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerSlugRoute = DealerSlugRouteImport.update({
  id: '/dealer/$slug',
  path: '/dealer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DubaiIntentRoute = DubaiIntentRouteImport.update({
  id: '/dubai/$intent',
  path: '/dubai/$intent',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSlugRoute = SellerSlugRouteImport.update({
  id: '/seller/$slug',
  path: '/seller/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsRoute = ApiV1ListingsRouteImport.update({
  id: '/api/v1/listings',
  path: '/api/v1/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyVehicleIndexRoute = BuyVehicleIndexRouteImport.update({
  id: '/buy/$vehicle/',
  path: '/buy/$vehicle/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentVehicleIndexRoute = RentVehicleIndexRouteImport.update({
  id: '/rent/$vehicle/',
  path: '/rent/$vehicle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsIdRoute = ApiV1ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ListingsRoute,
} as any)
const BuyVehicleAreaIndexRoute = BuyVehicleAreaIndexRouteImport.update({
  id: '/buy/$vehicle/$area/',
  path: '/buy/$vehicle/$area/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyVehicleAreaIdRoute = BuyVehicleAreaIdRouteImport.update({
  id: '/buy/$vehicle/$area/$id',
  path: '/buy/$vehicle/$area/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RentVehicleAreaIndexRoute = RentVehicleAreaIndexRouteImport.update({
  id: '/rent/$vehicle/$area/',
  path: '/rent/$vehicle/$area/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentVehicleAreaIdRoute = RentVehicleAreaIdRouteImport.update({
  id: '/rent/$vehicle/$area/$id',
  path: '/rent/$vehicle/$area/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/marketplace-disclaimer': typeof MarketplaceDisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/report': typeof ReportRoute
  '/report-listing': typeof ReportListingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/google-check': typeof ApiGoogleCheckRoute
  '/dealer/$slug': typeof DealerSlugRoute
  '/dubai/$intent': typeof DubaiIntentRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/post/$id': typeof PostIdRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/post/': typeof PostIndexRoute
  '/rent/': typeof RentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/listings': typeof ApiV1ListingsRouteWithChildren
  '/buy/$vehicle/': typeof BuyVehicleIndexRoute
  '/rent/$vehicle/': typeof RentVehicleIndexRoute
  '/api/v1/listings/$id': typeof ApiV1ListingsIdRoute
  '/buy/$vehicle/$area/$id': typeof BuyVehicleAreaIdRoute
  '/rent/$vehicle/$area/$id': typeof RentVehicleAreaIdRoute
  '/buy/$vehicle/$area/': typeof BuyVehicleAreaIndexRoute
  '/rent/$vehicle/$area/': typeof RentVehicleAreaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/marketplace-disclaimer': typeof MarketplaceDisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/report': typeof ReportRoute
  '/report-listing': typeof ReportListingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/google-check': typeof ApiGoogleCheckRoute
  '/dealer/$slug': typeof DealerSlugRoute
  '/dubai/$intent': typeof DubaiIntentRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/post/$id': typeof PostIdRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/buy': typeof BuyIndexRoute
  '/post': typeof PostIndexRoute
  '/rent': typeof RentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/listings': typeof ApiV1ListingsRouteWithChildren
  '/buy/$vehicle': typeof BuyVehicleIndexRoute
  '/rent/$vehicle': typeof RentVehicleIndexRoute
  '/api/v1/listings/$id': typeof ApiV1ListingsIdRoute
  '/buy/$vehicle/$area/$id': typeof BuyVehicleAreaIdRoute
  '/rent/$vehicle/$area/$id': typeof RentVehicleAreaIdRoute
  '/buy/$vehicle/$area': typeof BuyVehicleAreaIndexRoute
  '/rent/$vehicle/$area': typeof RentVehicleAreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/marketplace-disclaimer': typeof MarketplaceDisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/report': typeof ReportRoute
  '/report-listing': typeof ReportListingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/google-check': typeof ApiGoogleCheckRoute
  '/dealer/$slug': typeof DealerSlugRoute
  '/dubai/$intent': typeof DubaiIntentRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/post/$id': typeof PostIdRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/post/': typeof PostIndexRoute
  '/rent/': typeof RentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/listings': typeof ApiV1ListingsRouteWithChildren
  '/buy/$vehicle/': typeof BuyVehicleIndexRoute
  '/rent/$vehicle/': typeof RentVehicleIndexRoute
  '/api/v1/listings/$id': typeof ApiV1ListingsIdRoute
  '/buy/$vehicle/$area/$id': typeof BuyVehicleAreaIdRoute
  '/rent/$vehicle/$area/$id': typeof RentVehicleAreaIdRoute
  '/buy/$vehicle/$area/': typeof BuyVehicleAreaIndexRoute
  '/rent/$vehicle/$area/': typeof RentVehicleAreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/cookies'
    | '/disclaimer'
    | '/login'
    | '/marketplace-disclaimer'
    | '/privacy'
    | '/privacy-policy'
    | '/report'
    | '/report-listing'
    | '/robots.txt'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-and-conditions'
    | '/api/google-check'
    | '/dealer/$slug'
    | '/dubai/$intent'
    | '/locations/$slug'
    | '/post/$id'
    | '/seller/$slug'
    | '/account/'
    | '/admin/'
    | '/buy/'
    | '/post/'
    | '/rent/'
    | '/api/auth/$'
    | '/api/v1/listings'
    | '/buy/$vehicle/'
    | '/rent/$vehicle/'
    | '/api/v1/listings/$id'
    | '/buy/$vehicle/$area/$id'
    | '/rent/$vehicle/$area/$id'
    | '/buy/$vehicle/$area/'
    | '/rent/$vehicle/$area/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/cookies'
    | '/disclaimer'
    | '/login'
    | '/marketplace-disclaimer'
    | '/privacy'
    | '/privacy-policy'
    | '/report'
    | '/report-listing'
    | '/robots.txt'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-and-conditions'
    | '/api/google-check'
    | '/dealer/$slug'
    | '/dubai/$intent'
    | '/locations/$slug'
    | '/post/$id'
    | '/seller/$slug'
    | '/account'
    | '/admin'
    | '/buy'
    | '/post'
    | '/rent'
    | '/api/auth/$'
    | '/api/v1/listings'
    | '/buy/$vehicle'
    | '/rent/$vehicle'
    | '/api/v1/listings/$id'
    | '/buy/$vehicle/$area/$id'
    | '/rent/$vehicle/$area/$id'
    | '/buy/$vehicle/$area'
    | '/rent/$vehicle/$area'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/cookies'
    | '/disclaimer'
    | '/login'
    | '/marketplace-disclaimer'
    | '/privacy'
    | '/privacy-policy'
    | '/report'
    | '/report-listing'
    | '/robots.txt'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-and-conditions'
    | '/api/google-check'
    | '/dealer/$slug'
    | '/dubai/$intent'
    | '/locations/$slug'
    | '/post/$id'
    | '/seller/$slug'
    | '/account/'
    | '/admin/'
    | '/buy/'
    | '/post/'
    | '/rent/'
    | '/api/auth/$'
    | '/api/v1/listings'
    | '/buy/$vehicle/'
    | '/rent/$vehicle/'
    | '/api/v1/listings/$id'
    | '/buy/$vehicle/$area/$id'
    | '/rent/$vehicle/$area/$id'
    | '/buy/$vehicle/$area/'
    | '/rent/$vehicle/$area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LoginRoute: typeof LoginRoute
  MarketplaceDisclaimerRoute: typeof MarketplaceDisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReportRoute: typeof ReportRoute
  ReportListingRoute: typeof ReportListingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiGoogleCheckRoute: typeof ApiGoogleCheckRoute
  DealerSlugRoute: typeof DealerSlugRoute
  DubaiIntentRoute: typeof DubaiIntentRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PostIdRoute: typeof PostIdRoute
  SellerSlugRoute: typeof SellerSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BuyIndexRoute: typeof BuyIndexRoute
  PostIndexRoute: typeof PostIndexRoute
  RentIndexRoute: typeof RentIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ListingsRoute: typeof ApiV1ListingsRouteWithChildren
  BuyVehicleIndexRoute: typeof BuyVehicleIndexRoute
  RentVehicleIndexRoute: typeof RentVehicleIndexRoute
  BuyVehicleAreaIdRoute: typeof BuyVehicleAreaIdRoute
  RentVehicleAreaIdRoute: typeof RentVehicleAreaIdRoute
  BuyVehicleAreaIndexRoute: typeof BuyVehicleAreaIndexRoute
  RentVehicleAreaIndexRoute: typeof RentVehicleAreaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-disclaimer': {
      id: '/marketplace-disclaimer'
      path: '/marketplace-disclaimer'
      fullPath: '/marketplace-disclaimer'
      preLoaderRoute: typeof MarketplaceDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-listing': {
      id: '/report-listing'
      path: '/report-listing'
      fullPath: '/report-listing'
      preLoaderRoute: typeof ReportListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-check': {
      id: '/api/google-check'
      path: '/api/google-check'
      fullPath: '/api/google-check'
      preLoaderRoute: typeof ApiGoogleCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/$slug': {
      id: '/dealer/$slug'
      path: '/dealer/$slug'
      fullPath: '/dealer/$slug'
      preLoaderRoute: typeof DealerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai/$intent': {
      id: '/dubai/$intent'
      path: '/dubai/$intent'
      fullPath: '/dubai/$intent'
      preLoaderRoute: typeof DubaiIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$slug': {
      id: '/seller/$slug'
      path: '/seller/$slug'
      fullPath: '/seller/$slug'
      preLoaderRoute: typeof SellerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings': {
      id: '/api/v1/listings'
      path: '/api/v1/listings'
      fullPath: '/api/v1/listings'
      preLoaderRoute: typeof ApiV1ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$vehicle/': {
      id: '/buy/$vehicle/'
      path: '/buy/$vehicle'
      fullPath: '/buy/$vehicle/'
      preLoaderRoute: typeof BuyVehicleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$vehicle/': {
      id: '/rent/$vehicle/'
      path: '/rent/$vehicle'
      fullPath: '/rent/$vehicle/'
      preLoaderRoute: typeof RentVehicleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/$id': {
      id: '/api/v1/listings/$id'
      path: '/$id'
      fullPath: '/api/v1/listings/$id'
      preLoaderRoute: typeof ApiV1ListingsIdRouteImport
      parentRoute: typeof ApiV1ListingsRoute
    }
    '/buy/$vehicle/$area/': {
      id: '/buy/$vehicle/$area/'
      path: '/buy/$vehicle/$area'
      fullPath: '/buy/$vehicle/$area/'
      preLoaderRoute: typeof BuyVehicleAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$vehicle/$area/$id': {
      id: '/buy/$vehicle/$area/$id'
      path: '/buy/$vehicle/$area/$id'
      fullPath: '/buy/$vehicle/$area/$id'
      preLoaderRoute: typeof BuyVehicleAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$vehicle/$area/': {
      id: '/rent/$vehicle/$area/'
      path: '/rent/$vehicle/$area'
      fullPath: '/rent/$vehicle/$area/'
      preLoaderRoute: typeof RentVehicleAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$vehicle/$area/$id': {
      id: '/rent/$vehicle/$area/$id'
      path: '/rent/$vehicle/$area/$id'
      fullPath: '/rent/$vehicle/$area/$id'
      preLoaderRoute: typeof RentVehicleAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV1ListingsRouteChildren {
  ApiV1ListingsIdRoute: typeof ApiV1ListingsIdRoute
}

const ApiV1ListingsRouteChildren: ApiV1ListingsRouteChildren = {
  ApiV1ListingsIdRoute: ApiV1ListingsIdRoute,
}

const ApiV1ListingsRouteWithChildren = ApiV1ListingsRoute._addFileChildren(
  ApiV1ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  LoginRoute: LoginRoute,
  MarketplaceDisclaimerRoute: MarketplaceDisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReportRoute: ReportRoute,
  ReportListingRoute: ReportListingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiGoogleCheckRoute: ApiGoogleCheckRoute,
  DealerSlugRoute: DealerSlugRoute,
  DubaiIntentRoute: DubaiIntentRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PostIdRoute: PostIdRoute,
  SellerSlugRoute: SellerSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BuyIndexRoute: BuyIndexRoute,
  PostIndexRoute: PostIndexRoute,
  RentIndexRoute: RentIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ListingsRoute: ApiV1ListingsRouteWithChildren,
  BuyVehicleIndexRoute: BuyVehicleIndexRoute,
  RentVehicleIndexRoute: RentVehicleIndexRoute,
  BuyVehicleAreaIdRoute: BuyVehicleAreaIdRoute,
  RentVehicleAreaIdRoute: RentVehicleAreaIdRoute,
  BuyVehicleAreaIndexRoute: BuyVehicleAreaIndexRoute,
  RentVehicleAreaIndexRoute: RentVehicleAreaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
